# Generated by Django 3.0.4 on 2020-03-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200328_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userClass',
            field=models.CharField(max_length=100),
        ),
    ]
