# Generated by Django 3.0.4 on 2020-03-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200328_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userClass',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
