# Generated by Django 3.0.4 on 2020-04-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200330_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='account_userinfo',
        ),
    ]
