# Generated by Django 2.1 on 2020-04-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200405_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='avatar/%Y%m%d/', verbose_name='头像'),
        ),
    ]
