# Generated by Django 2.1 on 2020-04-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_auto_20200411_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
