# Generated by Django 3.0.4 on 2020-04-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamworkwrite',
            options={'ordering': ('-publish',), 'verbose_name': '工作概况', 'verbose_name_plural': '工作概况'},
        ),
        migrations.AlterModelTable(
            name='teamworkwrite',
            table='teamwork_teamworkwrite',
        ),
    ]
