# Generated by Django 3.0.4 on 2020-04-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='sid',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='tid',
            new_name='chuti_id',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='major',
            new_name='for_user',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='pid',
            new_name='timu_id',
        ),
    ]
