# Generated by Django 3.0.4 on 2020-04-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanage', '0004_auto_20200401_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='for_user',
            field=models.CharField(default='0', max_length=20, verbose_name='适用用户类别'),
        ),
    ]
