# Generated by Django 3.0.4 on 2020-04-01 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classmanage', '0005_auto_20200401_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='chuti_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
