# Generated by Django 3.0.4 on 2020-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanage', '0006_auto_20200401_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.ImageField(upload_to='classsubject/', verbose_name='题目'),
        ),
    ]
