# Generated by Django 3.0.4 on 2020-04-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanage', '0008_auto_20200401_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '单项图像标签题库', 'verbose_name_plural': '单项图像标签题库'},
        ),
    ]
