# Generated by Django 2.1 on 2020-04-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classmanage', '0009_auto_20200402_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': '答题升级模块', 'verbose_name_plural': '答题升级模块'},
        ),
    ]
