# Generated by Django 2.1 on 2020-04-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanage', '0010_auto_20200407_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.ImageField(upload_to='classsubject/', verbose_name='题目'),
        ),
    ]
